version: '3.9'

services:
  redis_db:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass securepassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  backend:
    build: ./backend
    depends_on:
      - redis_db
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
      REDIS_PASSWORD: securepassword
    ports:
      - 8081:8081
    restart: always

  frontend:
    build: ./frontend
    ports:
      - 8080:80

volumes:
  redis_data: